"""
Blog Generator Module - Automated blogging about goalie prospects
Supports multiple platforms and formats
"""

import os
from datetime import datetime
from pathlib import Path
from typing import List, Dict
import json


class BlogPost:
    """Represents a blog post about goalie prospects"""
    
    def __init__(self, title: str, content: str, tags: List[str] = None):
        self.title = title
        self.content = content
        self.tags = tags or []
        self.created_at = datetime.now().isoformat()
        
    def to_markdown(self) -> str:
        """Convert to markdown format"""
        tags_str = ", ".join([f"#{tag}" for tag in self.tags])
        return f"""---
title: {self.title}
date: {self.created_at}
tags: {tags_str}
---

# {self.title}

{self.content}

---
*Generated by GoalieScout AI Platform*
"""
    
    def to_html(self) -> str:
        """Convert to HTML format"""
        tags_html = " ".join([f'<span class="tag">#{tag}</span>' for tag in self.tags])
        content_html = self.content.replace("\n\n", "</p><p>").replace("\n", "<br>")
        return f"""<!DOCTYPE html>
<html>
<head>
    <title>{self.title}</title>
    <meta name="date" content="{self.created_at}">
</head>
<body>
    <article>
        <h1>{self.title}</h1>
        <div class="tags">{tags_html}</div>
        <div class="content">
            <p>{content_html}</p>
        </div>
        <footer>Generated by GoalieScout AI Platform - {self.created_at}</footer>
    </article>
</body>
</html>
"""


class BlogGenerator:
    """Generate blog posts about goalie prospects"""
    
    def __init__(self, output_dir: str = "blog_posts", ai_provider=None):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        self.ai_provider = ai_provider
        
    def generate_top_prospects_post(self, goalies: List[Dict], top_n: int = 10) -> BlogPost:
        """Generate a blog post about top prospects"""
        # Sort by AI score
        top_goalies = sorted(goalies, key=lambda x: x.get("ai_score", 0), reverse=True)[:top_n]
        
        title = f"Top {top_n} Goalie Prospects - {datetime.now().strftime('%B %Y')}"
        
        content = f"""The latest AI-powered analysis of goalie prospects across international leagues reveals some exciting talent. Here are the top {top_n} goalies to watch:

"""
        
        for idx, goalie in enumerate(top_goalies, 1):
            content += f"""
## {idx}. {goalie['name']} - {goalie.get('team', 'Unknown')} ({goalie.get('league', 'Unknown')})

**AI Score:** {goalie.get('ai_score', 0)}/100  
**Tier:** {goalie.get('tier', 'Unknown')}  
**Country:** {goalie.get('country', 'Unknown')}  
"""
            
            # Add injury status if available
            injury_data = goalie.get('injury_data', {})
            if injury_data:
                current_injury = injury_data.get('current_injury')
                if current_injury:
                    content += f"**Injury Status:** Currently injured ({current_injury.get('type', 'Unknown')})\n"
                else:
                    content += f"**Injury Status:** Healthy\n"
                
                rating = injury_data.get('injury_prone_rating', 'Unknown')
                content += f"**Injury History:** {rating} risk\n"
            
            content += f"\n{goalie.get('notes', 'No scouting notes available.')}\n"
            
            # Add NHL comparison if available
            from nhl_comparison import format_comparison_for_blog
            nhl_comp = goalie.get('nhl_comparison')
            if nhl_comp and nhl_comp.get('primary_comparison'):
                content += format_comparison_for_blog(nhl_comp)
            
            content += "\n---\n"
        
        tags = ["goalie prospects", "hockey", "scouting", "AI analysis"]
        return BlogPost(title, content, tags)
    
    def generate_league_spotlight(self, goalies: List[Dict], league: str) -> BlogPost:
        """Generate a blog post spotlighting a specific league"""
        league_goalies = [g for g in goalies if g.get('league') == league]
        
        if not league_goalies:
            return None
        
        title = f"{league} Goalie Spotlight - {datetime.now().strftime('%B %Y')}"
        
        content = f"""An in-depth look at goaltending talent in the {league}. Our AI-powered scouting system has analyzed {len(league_goalies)} goalies in this league.

"""
        
        # Sort by score
        league_goalies.sort(key=lambda x: x.get("ai_score", 0), reverse=True)
        
        for goalie in league_goalies[:5]:  # Top 5 from league
            content += f"""
### {goalie['name']} - {goalie.get('team', 'Unknown')}

**AI Score:** {goalie.get('ai_score', 0)}/100  
**Tier:** {goalie.get('tier', 'Unknown')}  

{goalie.get('notes', 'No scouting notes available.')}

"""
        
        tags = ["goalie prospects", league, "hockey scouting", "league spotlight"]
        return BlogPost(title, content, tags)
    
    def generate_rising_stars_post(self, goalies: List[Dict]) -> BlogPost:
        """Generate a blog post about 'Sleeper' prospects"""
        sleepers = [g for g in goalies if g.get('tier') == 'Sleeper']
        
        title = f"Rising Stars: Sleeper Goalie Prospects - {datetime.now().strftime('%B %Y')}"
        
        content = """These under-the-radar goalie prospects could be the next breakout stars. Our AI analysis has identified these 'sleeper' candidates who deserve more attention:

"""
        
        for goalie in sleepers[:10]:
            content += f"""
### {goalie['name']} - {goalie.get('team', 'Unknown')} ({goalie.get('league', 'Unknown')})

**Country:** {goalie.get('country', 'Unknown')}  
**AI Score:** {goalie.get('ai_score', 0)}/100  

{goalie.get('notes', 'No scouting notes available.')}

---
"""
        
        tags = ["sleeper prospects", "hockey", "goalie scouting", "hidden gems"]
        return BlogPost(title, content, tags)
    
    def save_post(self, post: BlogPost, format: str = "markdown"):
        """Save blog post to file"""
        if not post:
            return
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_title = "".join(c if c.isalnum() or c in (' ', '-', '_') else '_' for c in post.title)
        safe_title = safe_title.replace(' ', '_')[:50]
        
        if format == "markdown":
            filename = self.output_dir / f"{timestamp}_{safe_title}.md"
            content = post.to_markdown()
        elif format == "html":
            filename = self.output_dir / f"{timestamp}_{safe_title}.html"
            content = post.to_html()
        else:
            filename = self.output_dir / f"{timestamp}_{safe_title}.txt"
            content = f"{post.title}\n\n{post.content}"
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"[✓] Blog post saved: {filename}")
        return filename
    
    def generate_all_posts(self, goalies: List[Dict]) -> List[str]:
        """Generate all blog posts"""
        saved_files = []
        
        # Top prospects post
        top_post = self.generate_top_prospects_post(goalies, top_n=10)
        saved_files.append(self.save_post(top_post, format="markdown"))
        
        # Rising stars post
        rising_post = self.generate_rising_stars_post(goalies)
        if rising_post:
            saved_files.append(self.save_post(rising_post, format="markdown"))
        
        # League spotlight posts (for leagues with data)
        leagues = set(g.get('league') for g in goalies if g.get('league'))
        for league in list(leagues)[:3]:  # Limit to 3 leagues to avoid spam
            league_post = self.generate_league_spotlight(goalies, league)
            if league_post:
                saved_files.append(self.save_post(league_post, format="markdown"))
        
        return [f for f in saved_files if f]
