"""Content generation tools for scouting reports and social media."""

from typing import Dict, Any, Optional
import os
from pathlib import Path
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generate scouting reports in various formats."""
    
    def __init__(self, output_dir: str = "./reports"):
        """Initialize report generator.
        
        Args:
            output_dir: Directory for output files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_markdown_report(self, profile_data: Dict[str, Any], ai_report: str) -> str:
        """Generate Markdown format report.
        
        Args:
            profile_data: Goalie profile dictionary
            ai_report: AI-generated report content
            
        Returns:
            Markdown formatted report
        """
        demographics = profile_data.get('demographics', {})
        league = profile_data.get('league', 'Unknown')
        
        markdown = f"""# Scouting Report: {demographics.get('name', 'Unknown')}

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Player Information

- **Name:** {demographics.get('name', 'Unknown')}
- **Country:** {demographics.get('country', 'Unknown')}
- **Date of Birth:** {demographics.get('date_of_birth', 'Unknown')}
- **Height:** {demographics.get('height', 'N/A')}
- **Weight:** {demographics.get('weight', 'N/A')}
- **Catches:** {demographics.get('catches', 'N/A')}
- **Current League:** {league}
- **Current Team:** {profile_data.get('current_team', 'N/A')}

## Performance Metrics

"""
        
        # Add performance metrics
        metrics = profile_data.get('performance_metrics', [])
        if metrics:
            markdown += "| Season | GP | W | L | SV% | GAA | SO |\n"
            markdown += "|--------|----|----|----|----|----|----||\n"
            
            for m in metrics[-5:]:  # Last 5 seasons
                markdown += f"| {m.get('season', 'N/A')} | {m.get('games_played', 0)} | {m.get('wins', 0)} | {m.get('losses', 0)} | {m.get('save_percentage', 0):.3f} | {m.get('goals_against_average', 0):.2f} | {m.get('shutouts', 0)} |\n"
        else:
            markdown += "*No performance metrics available*\n"
        
        markdown += "\n## AI Analysis\n\n"
        
        # Add AI analysis
        ai_analysis = profile_data.get('ai_analysis')
        if ai_analysis:
            markdown += f"**Overall Rating:** {ai_analysis.get('overall_rating', 0)}/100\n\n"
            markdown += f"**Potential Rating:** {ai_analysis.get('potential_rating', 0)}/100\n\n"
            markdown += f"**NHL Readiness:** {ai_analysis.get('nhl_readiness', 'Unknown')}\n\n"
            
            strengths = ai_analysis.get('strengths', [])
            if strengths:
                markdown += "### Strengths\n\n"
                for strength in strengths:
                    markdown += f"- {strength}\n"
                markdown += "\n"
            
            weaknesses = ai_analysis.get('weaknesses', [])
            if weaknesses:
                markdown += "### Weaknesses\n\n"
                for weakness in weaknesses:
                    markdown += f"- {weakness}\n"
                markdown += "\n"
            
            markdown += f"### Scouting Notes\n\n{ai_analysis.get('scouting_notes', 'N/A')}\n\n"
        
        # Add detailed AI report
        if ai_report:
            markdown += f"## Detailed Scouting Report\n\n{ai_report}\n\n"
        
        # Add NHL comparisons
        comparisons = profile_data.get('nhl_comparisons', [])
        if comparisons:
            markdown += "## NHL Comparisons\n\n"
            for comp in comparisons:
                markdown += f"### {comp.get('comparable_player', 'Unknown')}\n"
                markdown += f"**Similarity:** {comp.get('similarity_score', 0):.1f}%\n\n"
                markdown += f"{comp.get('comparison_notes', 'N/A')}\n\n"
        
        # Add injury history
        injuries = profile_data.get('injury_history', [])
        if injuries:
            markdown += "## Injury History\n\n"
            markdown += "| Date | Type | Severity | Status |\n"
            markdown += "|------|------|----------|--------|\n"
            for injury in injuries:
                markdown += f"| {injury.get('date', 'N/A')} | {injury.get('injury_type', 'N/A')} | {injury.get('severity', 'N/A')} | {injury.get('status', 'N/A')} |\n"
            markdown += "\n"
        
        markdown += "---\n\n*Report generated by Black Ops Goalie Scouting Platform*\n"
        
        return markdown
    
    def generate_html_report(self, profile_data: Dict[str, Any], ai_report: str) -> str:
        """Generate HTML format report.
        
        Args:
            profile_data: Goalie profile dictionary
            ai_report: AI-generated report content
            
        Returns:
            HTML formatted report
        """
        demographics = profile_data.get('demographics', {})
        
        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Scouting Report: {demographics.get('name', 'Unknown')}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .header {{
            background-color: #003366;
            color: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
        }}
        .section {{
            background-color: white;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
        }}
        th, td {{
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background-color: #f0f0f0;
        }}
        .rating {{
            font-size: 24px;
            font-weight: bold;
            color: #003366;
        }}
        ul {{
            list-style-type: none;
            padding-left: 0;
        }}
        li::before {{
            content: "✓ ";
            color: #003366;
            font-weight: bold;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Scouting Report: {demographics.get('name', 'Unknown')}</h1>
        <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    </div>
    
    <div class="section">
        <h2>Player Information</h2>
        <table>
            <tr><td><strong>Name:</strong></td><td>{demographics.get('name', 'Unknown')}</td></tr>
            <tr><td><strong>Country:</strong></td><td>{demographics.get('country', 'Unknown')}</td></tr>
            <tr><td><strong>Date of Birth:</strong></td><td>{demographics.get('date_of_birth', 'Unknown')}</td></tr>
            <tr><td><strong>Height:</strong></td><td>{demographics.get('height', 'N/A')}</td></tr>
            <tr><td><strong>Weight:</strong></td><td>{demographics.get('weight', 'N/A')}</td></tr>
            <tr><td><strong>Catches:</strong></td><td>{demographics.get('catches', 'N/A')}</td></tr>
            <tr><td><strong>Current League:</strong></td><td>{profile_data.get('league', 'Unknown')}</td></tr>
        </table>
    </div>
"""
        
        # Add AI analysis section
        ai_analysis = profile_data.get('ai_analysis')
        if ai_analysis:
            html += f"""
    <div class="section">
        <h2>AI Analysis</h2>
        <p><strong>Overall Rating:</strong> <span class="rating">{ai_analysis.get('overall_rating', 0)}/100</span></p>
        <p><strong>Potential Rating:</strong> <span class="rating">{ai_analysis.get('potential_rating', 0)}/100</span></p>
        <p><strong>NHL Readiness:</strong> {ai_analysis.get('nhl_readiness', 'Unknown')}</p>
        
        <h3>Strengths</h3>
        <ul>
"""
            for strength in ai_analysis.get('strengths', []):
                html += f"            <li>{strength}</li>\n"
            
            html += """        </ul>
        
        <h3>Weaknesses</h3>
        <ul>
"""
            for weakness in ai_analysis.get('weaknesses', []):
                html += f"            <li>{weakness}</li>\n"
            
            html += """        </ul>
    </div>
"""
        
        html += """
    <div class="section">
        <p><em>Report generated by Black Ops Goalie Scouting Platform</em></p>
    </div>
</body>
</html>
"""
        
        return html
    
    def save_report(self, content: str, player_name: str, format_type: str = "markdown") -> str:
        """Save report to file.
        
        Args:
            content: Report content
            player_name: Player name for filename
            format_type: Format type (markdown or html)
            
        Returns:
            Path to saved file
        """
        extension = "md" if format_type == "markdown" else "html"
        safe_name = player_name.replace(" ", "_").replace("/", "_")
        filename = f"{safe_name}_report_{datetime.now().strftime('%Y%m%d')}.{extension}"
        filepath = self.output_dir / filename
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        logger.info(f"Report saved to {filepath}")
        return str(filepath)


class BlogGenerator:
    """Generate blog posts about goalies."""
    
    def __init__(self, output_dir: str = "./content/blog"):
        """Initialize blog generator.
        
        Args:
            output_dir: Directory for blog posts
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_player_spotlight(self, profile_data: Dict[str, Any]) -> str:
        """Generate player spotlight blog post.
        
        Args:
            profile_data: Goalie profile dictionary
            
        Returns:
            Blog post content in Markdown
        """
        demographics = profile_data.get('demographics', {})
        name = demographics.get('name', 'Unknown')
        
        post = f"""---
title: "Player Spotlight: {name}"
date: {datetime.now().strftime('%Y-%m-%d')}
author: Black Ops Scouting Team
tags: [goalie, scouting, {profile_data.get('league', 'hockey')}]
---

# Player Spotlight: {name}

{name} is an exciting goalie prospect currently playing in the {profile_data.get('league', 'Unknown')} league. 
"""
        
        ai_analysis = profile_data.get('ai_analysis')
        if ai_analysis:
            post += f"""
## Quick Stats

- **Overall Rating:** {ai_analysis.get('overall_rating', 0)}/100
- **Potential:** {ai_analysis.get('potential_rating', 0)}/100
- **NHL Readiness:** {ai_analysis.get('nhl_readiness', 'Unknown')}

## What Makes {name.split()[0]} Special

"""
            strengths = ai_analysis.get('strengths', [])
            if strengths:
                post += f"{strengths[0]} stands out as a key strength in their game. "
        
        post += f"""

## Performance Overview

"""
        
        metrics = profile_data.get('performance_metrics', [])
        if metrics and len(metrics) > 0:
            latest = metrics[-1]
            post += f"""In their most recent season, {name.split()[0]} posted a {latest.get('save_percentage', 0):.3f} save percentage 
with a {latest.get('goals_against_average', 0):.2f} GAA across {latest.get('games_played', 0)} games.
"""
        
        post += f"""

## Final Thoughts

{name} represents an intriguing prospect worth monitoring closely. Stay tuned for more updates!

---

*Follow us for more goalie scouting insights and player spotlights.*
"""
        
        return post
    
    def save_blog_post(self, content: str, player_name: str) -> str:
        """Save blog post to file.
        
        Args:
            content: Blog post content
            player_name: Player name for filename
            
        Returns:
            Path to saved file
        """
        safe_name = player_name.replace(" ", "_").replace("/", "_")
        filename = f"{safe_name}_spotlight_{datetime.now().strftime('%Y%m%d')}.md"
        filepath = self.output_dir / filename
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        logger.info(f"Blog post saved to {filepath}")
        return str(filepath)


class SocialMediaManager:
    """Manage social media posts."""
    
    def __init__(self):
        """Initialize social media manager."""
        self.twitter_configured = self._check_twitter_config()
    
    def _check_twitter_config(self) -> bool:
        """Check if Twitter API credentials are configured."""
        required_keys = [
            'TWITTER_API_KEY',
            'TWITTER_API_SECRET',
            'TWITTER_ACCESS_TOKEN',
            'TWITTER_ACCESS_SECRET'
        ]
        
        return all(os.getenv(key) for key in required_keys)
    
    def create_player_tweet(self, profile_data: Dict[str, Any]) -> str:
        """Create tweet text for player spotlight.
        
        Args:
            profile_data: Goalie profile dictionary
            
        Returns:
            Tweet text (max 280 characters)
        """
        demographics = profile_data.get('demographics', {})
        name = demographics.get('name', 'Unknown')
        league = profile_data.get('league', 'Unknown')
        
        ai_analysis = profile_data.get('ai_analysis')
        
        if ai_analysis:
            rating = ai_analysis.get('overall_rating', 0)
            tweet = f"🥅 Player Spotlight: {name}\n"
            tweet += f"📊 Rating: {rating}/100\n"
            tweet += f"🏒 League: {league}\n"
            
            strengths = ai_analysis.get('strengths', [])
            if strengths:
                tweet += f"⭐ {strengths[0]}\n"
            
            tweet += "\n#HockeyScout #GoalieScouting"
        else:
            tweet = f"🥅 New goalie profile: {name} ({league})\n#HockeyScout #GoalieScouting"
        
        # Ensure tweet is within Twitter's character limit
        if len(tweet) > 280:
            tweet = tweet[:277] + "..."
        
        return tweet
    
    def post_to_twitter(self, tweet_text: str) -> bool:
        """Post tweet to Twitter/X.
        
        Args:
            tweet_text: Tweet content
            
        Returns:
            True if successful
        """
        if not self.twitter_configured:
            logger.warning("Twitter API not configured")
            return False
        
        try:
            import tweepy
            
            auth = tweepy.OAuthHandler(
                os.getenv('TWITTER_API_KEY'),
                os.getenv('TWITTER_API_SECRET')
            )
            auth.set_access_token(
                os.getenv('TWITTER_ACCESS_TOKEN'),
                os.getenv('TWITTER_ACCESS_SECRET')
            )
            
            api = tweepy.API(auth)
            api.update_status(tweet_text)
            
            logger.info("Tweet posted successfully")
            return True
            
        except Exception as e:
            logger.error(f"Error posting to Twitter: {e}")
            return False
    
    def create_ranking_tweet(self, rankings: list) -> str:
        """Create tweet for goalie rankings.
        
        Args:
            rankings: List of ranked goalies
            
        Returns:
            Tweet text
        """
        tweet = "🥅 Top Goalie Rankings 🥅\n\n"
        
        for i, goalie in enumerate(rankings[:5], 1):
            name = goalie.get('name', 'Unknown')
            tweet += f"{i}. {name}\n"
        
        tweet += "\n#HockeyScout #GoalieRankings"
        
        if len(tweet) > 280:
            tweet = tweet[:277] + "..."
        
        return tweet
